comment:
  layout: header, diff, flags

coverage:
  status:
    default_rules:
      threshold: 10%

    project:
      pages:
        flags:
          - functionals
        paths:
          - apps/pages

      worker:
        flags:
          - functionals
        paths:
          - apps/worker

      backend:
        flags:
          - functionals
        paths:
          - packages/backend

      frontend:
        flags:
          - functionals
        paths:
          - packages/frontend
