name: Code
run-name: 'ci(${{ github.event.pull_request.head.ref || github.ref_name }}): quality check'

on:
  pull_request_target:
    branches: [main]
    types: [opened, synchronize]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          persist-credentials: false

      - name: Set up Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 24
          cache: true

      - name: Install
        run: vp install

      - name: Lint
        run: vp check

  distribute:
    name: Distribute
    needs: lint
    uses: ./.github/workflows/dist.yml
    with:
      branch-name: ${{ github.event.pull_request.head.ref || github.ref_name }}
    secrets: inherit
