name: Code
run-name: 'ci(${{ github.event.pull_request.head.ref || github.ref_name }}): quality check'

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  test-pkg:
    name: Test `${{ matrix.pkg }}`
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        pkg: ['@feryardiant/lvp-utils', '@feryardiant/lvp-web']

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          persist-credentials: false

      - name: Set up Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 24
          cache: true

      - name: Install
        run: vp install

      - name: Lint
        run: vp check

      - name: Test
        run: vp run ${{ matrix.pkg }}#test

  test-e2e:
    name: End-to-end Test
    runs-on: ubuntu-latest
    needs: test-pkg

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          persist-credentials: false

      - name: Set up Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 24
          cache: true

      - name: Install
        run: vp install

      - name: Test
        run: vp test --project @feryardiant/learn-viteplus

  distribute:
    name: Distribute
    needs: test-e2e
    if: github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/dist.yml
    with:
      branch-name: ${{ github.event.pull_request.head.ref || github.ref_name }}
    secrets: inherit
