name: Distribute
run-name: 'dist(${{ inputs.branch-name || github.ref_name }}): build & deploy'

on:
  workflow_call:
    inputs:
      branch-name:
        required: true
        type: string
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
      CLOUDFLARE_ACCOUNT_ID:
        required: true
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-dist-${{ inputs.branch-name || github.ref_name }}
  cancel-in-progress: true

env:
  BRANCH_NAME: ${{ inputs.branch-name || github.ref_name }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      branch-name: ${{ steps.build.outputs.branch-name }}
      deploy-env: ${{ steps.build.outputs.deploy-env }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ env.BRANCH_NAME }}
          persist-credentials: false

      - name: Set up Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 24
          cache: true

      - name: Install
        run: vp install

      - name: Build
        id: build
        run: |
          vp run -r build

          DEPLOY_ENV=$([[ "$BRANCH_NAME" == "main" ]] && echo "production" || echo "preview")
          echo "deploy-env=$DEPLOY_ENV" >> $GITHUB_OUTPUT

      - name: Store
        uses: actions/upload-artifact@v7
        with:
          overwrite: true
          name: website
          path: apps/website/dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: ${{ needs.build.outputs.deploy-env }}
      url: ${{ steps.deploy.outputs.deployment-url }}

    permissions:
      contents: read

    steps:
      - name: Prepare
        uses: actions/download-artifact@v8
        with:
          name: website

      - name: Build & Deploy Worker
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: |
            pages deploy . --project-name=learn-viteplus --branch=${{ env.BRANCH_NAME }}
