name: Distribute
run-name: 'dist(${{ inputs.branch-name || github.ref_name }}): build & deploy'

on:
  workflow_call:
    inputs:
      branch-name:
        required: true
        type: string
      sha:
        required: false
        type: string
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
      CLOUDFLARE_ACCOUNT_ID:
        required: true
      CODECOV_TOKEN:
        required: true
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-dist-${{ inputs.branch-name || github.ref_name }}
  cancel-in-progress: true

env:
  BRANCH_NAME: ${{ inputs.branch-name || github.ref_name }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      deploy-env: ${{ steps.build.outputs.deploy-env }}
      should-deploy: ${{ steps.build.outputs.should-deploy || 0 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ env.BRANCH_NAME }}
          persist-credentials: false

      - name: Set up Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          cache: true
          run-install: true

      - name: Set up vite build cache
        uses: actions/cache@v5
        if: env.BRANCH_NAME == 'main'
        with:
          path: ${{ github.workspace }}/node_modules/.vite/task-cache
          key: vite-build-${{ hashFiles('**/bun.lock') }}
          restore-keys: vite-build-

      - name: Build
        id: build
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          COMMIT_SHA: ${{ inputs.sha }}
          DEPLOY_ENV: ${{ env.BRANCH_NAME == 'main' && 'production' || 'preview' }}
        run: |
          vp run -r build -m $DEPLOY_ENV
          node ./scripts/upload-bundle-stats.mjs

          echo "deploy-env=$DEPLOY_ENV" >> $GITHUB_OUTPUT

      - name: Store build artifact
        uses: actions/upload-artifact@v7
        if: steps.build.outputs.should-deploy == 1
        with:
          name: website-${{ steps.build.outputs.deploy-env }}
          path: apps/website/dist
          include-hidden-files: true
          overwrite: true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: needs.build.outputs.should-deploy == 1
    needs: build

    environment:
      name: ${{ needs.build.outputs.deploy-env }}
      url: ${{ steps.deploy.outputs.pages-deployment-alias-url || vars.BASE_URL }}

    permissions:
      contents: read

    steps:
      - name: Prepare
        uses: actions/download-artifact@v8
        with:
          name: website-${{ needs.build.outputs.deploy-env }}
          path: to-deploy

      - name: Merge build outputs
        run: |
          mv to-deploy/ssr dist
          cp -r to-deploy/client/. dist/
          mv dist/index.js dist/_worker.js
          ls -lah dist/

      - name: Build & Deploy Worker
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: |
            pages deploy dist --project-name=learn-viteplus --branch=${{ env.BRANCH_NAME }}
