name: Distribute
run-name: 'dist(${{ inputs.branch-name || github.ref_name }}): build & deploy'

on:
  workflow_call:
    inputs:
      branch-name:
        required: true
        type: string
      sha:
        required: false
        type: string
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
      CLOUDFLARE_ACCOUNT_ID:
        required: true
      CODECOV_TOKEN:
        required: true
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-dist-${{ inputs.branch-name || github.ref_name }}
  cancel-in-progress: true

env:
  BRANCH_NAME: ${{ inputs.branch-name || github.ref_name }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      deploy-env: ${{ steps.build.outputs.deploy-env }}
      should-deploy: ${{ steps.build.outputs.should-deploy || 0 }}

    permissions:
      contents: read

    environment:
      name: ${{ steps.env.outputs.target }}
      # url: ${{ steps.deploy.outputs.pages-deployment-alias-url || vars.BASE_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ env.BRANCH_NAME }}
          persist-credentials: false

      - name: Set up Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          cache: true
          run-install: true

      - name: Set up vite build cache
        uses: actions/cache@v5
        if: env.BRANCH_NAME == 'main'
        with:
          path: ${{ github.workspace }}/node_modules/.vite/task-cache
          key: vite-build-${{ hashFiles('**/bun.lock') }}
          restore-keys: vite-build-

      - name: Prepare
        id: env
        env:
          TARGET_ENV: ${{ env.BRANCH_NAME == 'main' && 'production' || 'preview' }}
        run: |
          echo "CLOUDFLARE_ENV=$TARGET_ENV" >> $GITHUB_ENV
          echo "target=$TARGET_ENV" >> $GITHUB_OUTPUT

      - name: Build
        id: build
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          COMMIT_SHA: ${{ inputs.sha }}
        run: |
          vp run -r build -m $CLOUDFLARE_ENV
          node ./scripts/upload-bundle-stats.ts

      - name: Deploy
        id: deploy
        if: steps.build.outputs.should-deploy == 1
        working-directory: apps/website
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          vp exec --filter lvp-web wrangler deploy

      # - name: Deploy
      #   id: deploy
      #   if: steps.build.outputs.should-deploy == 1
      #   uses: cloudflare/wrangler-action@v4
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #     environment: ${{ steps.env.outputs.target }}
      #     command: |
      #       deploy --cwd ./apps/website
